In [2]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_deriv(y):
    return y * (1 - y)

def tanh(x):
    return np.tanh(x)

def tanh_deriv(y):
    return 1 - y**2

def swish(x):
    return x * sigmoid(x)

def swish_deriv(x):
    s = sigmoid(x)
    return s + x * s * (1 - s)

def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

def leaky_relu_deriv(x, alpha=0.01):
    return np.where(x > 0, 1, alpha)

X = np.array([[1, 1, 0, 1]])
Y = np.array([[1]])

l = 0.67
t = 0.0005

W = np.array([
    [ 0.3,  0.1],
    [-0.2,  0.4],
    [ 0.2, -0.3],
    [ 0.1,  0.4]
])
B = np.array([[0.2, 0.1]])
V = np.array([
    [-0.3],
    [ 0.2]
])
C = np.array([[-0.3]])

e = 0
p = False

act = swish
act_deriv = lambda z: swish_deriv(z)

while True:
    e += 1
    z = np.dot(X, W) + B
    h = act(z)
    u = np.dot(h, V) + C
    o = sigmoid(u)
    d = Y - o
    do = d * sigmoid_deriv(o)
    dh = do.dot(V.T) * act_deriv(z)
    V += l * h.T.dot(do)
    C += l * do
    W += l * X.T.dot(dh)
    B += l * dh
    if not p:
        print("\n--- First Epoch ---")
        print("Output (O):", o)
        print("Error (D - O):", d)
        print("Updated W1:\n", W)
        print("Updated b1:\n", B)
        print("Updated W2:\n", V)
        print("Updated b2:\n", C)
        p = True
    if abs(d[0][0]) < t:
        print("\n--- Last Epoch ---")
        print("Epoch:", e)
        print("Output (O):", o)
        print("Error (D - O):", d)
        print("Final W1:\n", W)
        print("Final b1:\n", B)
        print("Final W2:\n", V)
        print("Final b2:\n", C)
        break



--- First Epoch ---
Output (O): [[0.44383039]]
Error (D - O): [[0.55616961]]
Updated W1:
 [[ 0.28082734  0.11706594]
 [-0.21917266  0.41706594]
 [ 0.2        -0.3       ]
 [ 0.08082734  0.41706594]]
Updated b1:
 [[0.18082734 0.11706594]]
Updated W2:
 [[-0.27797243]
 [ 0.26724477]]
Updated b2:
 [[-0.20801726]]

--- Last Epoch ---
Epoch: 105869
Output (O): [[0.9995]]
Error (D - O): [[0.0005]]
Final W1:
 [[ 0.16912821  0.83848973]
 [-0.33087179  1.13848973]
 [ 0.2        -0.3       ]
 [-0.03087179  1.13848973]]
Final b1:
 [[0.06912821 0.83848973]]
Final W2:
 [[-0.2355313 ]
 [ 1.79034502]]
Final b2:
 [[0.6410225]]
