In [3]:
import numpy as np

# Sigmoid activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(y):
    return y * (1 - y)

# Input and desired output
X = np.array([[1, 1, 0, 1]])
y = np.array([[1]])

# Learning rate and stopping condition
lr = 0.8
tolerance = 0.001

# Initial weights & biases (Table 10.7)
W1 = np.array([
    [ 0.3,  0.1],
    [-0.2,  0.4],
    [ 0.2, -0.3],
    [ 0.1,  0.4]
])
b1 = np.array([[0.2, 0.1]])

W2 = np.array([
    [-0.3],
    [ 0.2]
])
b2 = np.array([[-0.3]])

epoch = 0
first_epoch_printed = False

while True:
    epoch += 1

    # Forward pass
    z1 = np.dot(X, W1) + b1
    h = sigmoid(z1)

    z2 = np.dot(h, W2) + b2
    o = sigmoid(z2)

    # Error
    error = y - o
    delta_out = error * sigmoid_derivative(o)
    delta_hidden = delta_out.dot(W2.T) * sigmoid_derivative(h)
    W2 += lr * h.T.dot(delta_out)
    b2 += lr * delta_out
    W1 += lr * X.T.dot(delta_hidden)
    b1 += lr * delta_hidden
    if not first_epoch_printed:
        print("\n--- First Epoch ---")
        print("Output (O):", o)
        print("Error (D - O):", error)
        print("Updated W1:\n", W1)
        print("Updated b1:\n", b1)
        print("Updated W2:\n", W2)
        print("Updated b2:\n", b2)
        first_epoch_printed = True
    if abs(error[0][0]) < tolerance:
        print("\n--- Last Epoch (Converged) ---")
        print("Output (O):", o)
        print("Error (D - O):", error)
        print("Updated W1:\n", W1)
        print("Updated b1:\n", b1)
        print("Updated W2:\n", W2)
        print("Updated b2:\n", b2)
        break


--- First Epoch ---
Output (O): [[0.4174149]]
Error (D - O): [[0.5825851]]
Updated W1:
 [[ 0.29183078  0.10445673]
 [-0.20816922  0.40445673]
 [ 0.2        -0.3       ]
 [ 0.09183078  0.40445673]]
Updated b1:
 [[0.19183078 0.10445673]]
Updated W2:
 [[-0.23214576]
 [ 0.28285693]]
Updated b2:
 [[-0.1866617]]

--- Last Epoch (Converged) ---
Output (O): [[0.999]]
Error (D - O): [[0.001]]
Updated W1:
 [[ 0.65303566  0.54725795]
 [ 0.15303566  0.84725795]
 [ 0.2        -0.3       ]
 [ 0.45303566  0.84725795]]
Updated b1:
 [[0.55303566 0.54725795]]
Updated W2:
 [[1.77082377]
 [2.78206443]]
Updated b2:
 [[2.76359402]]


In [4]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(y):
    return y * (1 - y)

X = np.array([[1, 1, 0, 1]])
y = np.array([[1]])

lr = 0.8
tolerance = 0.001

# Slightly altered initial weights & biases
W1 = np.array([
    [ 0.25,  0.15],
    [-0.25,  0.35],
    [ 0.15, -0.25],
    [ 0.05,  0.45]
])
b1 = np.array([[0.25, 0.05]])

W2 = np.array([
    [-0.25],
    [ 0.25]
])
b2 = np.array([[-0.25]])

epoch = 0
first_epoch_printed = False

while True:
    epoch += 1

    z1 = np.dot(X, W1) + b1
    h = sigmoid(z1)

    z2 = np.dot(h, W2) + b2
    o = sigmoid(z2)

    error = y - o
    delta_out = error * sigmoid_derivative(o)
    delta_hidden = delta_out.dot(W2.T) * sigmoid_derivative(h)

    W2 += lr * h.T.dot(delta_out)
    b2 += lr * delta_out
    W1 += lr * X.T.dot(delta_hidden)
    b1 += lr * delta_hidden

    if not first_epoch_printed:
        print("\n--- First Epoch ---")
        print("Output (O):", o)
        print("Error (D - O):", error)
        print("Updated W1:\n", W1)
        print("Updated b1:\n", b1)
        print("Updated W2:\n", W2)
        print("Updated b2:\n", b2)
        first_epoch_printed = True

    if abs(error[0][0]) < tolerance:
        print("\n--- Last Epoch (Converged) ---")
        print("Output (O):", o)
        print("Error (D - O):", error)
        print("Updated W1:\n", W1)
        print("Updated b1:\n", b1)
        print("Updated W2:\n", W2)
        print("Updated b2:\n", b2)
        break



--- First Epoch ---
Output (O): [[0.44748292]]
Error (D - O): [[0.55251708]]
Updated W1:
 [[ 0.24332113  0.15537165]
 [-0.25667887  0.35537165]
 [ 0.15       -0.25      ]
 [ 0.04332113  0.45537165]]
Updated b1:
 [[0.24332113 0.05537165]]
Updated W2:
 [[-0.18722244]
 [ 0.32989324]]
Updated b2:
 [[-0.14071568]]

--- Last Epoch (Converged) ---
Output (O): [[0.999]]
Error (D - O): [[0.001]]
Updated W1:
 [[ 0.61644541  0.60001525]
 [ 0.11644541  0.80001525]
 [ 0.15       -0.25      ]
 [ 0.41644541  0.90001525]]
Updated b1:
 [[0.61644541 0.50001525]]
Updated W2:
 [[1.75039851]
 [2.80254867]]
Updated b2:
 [[2.77013298]]
